replicaCount: 1

image:
  tag: "dev-latest"

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/appdb-dev"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"  # For dev: recreate schema

resources:
  limits:
    cpu: "0.3"
    memory: "256Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

postgres:
  resources:
    limits:
      cpu: "0.3"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "128Mi"
  storage:
    size: "500Mi"  # Smaller storage for dev
  credentials:
    database: "appdb-dev"